test

diff --git a/.github/workflows/run-tests.yml b/.github/workflows/run-tests.yml
--- a/.github/workflows/run-tests.yml
+++ b/.github/workflows/run-tests.yml
@@ -8,8 +8,45 @@ on:
       - master
 
 jobs:
+  Build-and-Test-Qemu:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Install qemu and required tools
+        run: >
+          sudo apt update && 
+          sudo apt -y install qemu-system-x86 cloud-image-utils cpu-checker cloud-image-utils wget openssh-client
+      - name: Check kvm support
+        run: kvm-ok
+      - name: Prepare cloud-init image disk
+        run: |
+          ssh-keygen -t ed25519 -b 512 -q -N "" -f ssh-key
+          echo "instance-id: $(uuidgen || echo i-abcdefg)" > init-meta
+          echo "#cloud-config" > init-data
+          echo "package_update: true" >> init-data
+          echo "package_upgrade: true" >> init-data
+          echo "package_reboot_if_required: true" >> init-data
+          echo "users:" >> init-data
+          echo "  - default" >> init-data
+          echo "  - name: user" >> init-data
+          echo "    shell: /bin/bash" >> init-data
+          echo "    home: /dev/shm/user" >> init-data
+          echo "    sudo: ALL=(ALL) NOPASSWD:ALL" >> init-data
+          echo "    ssh_authorized_keys:" >> init-data
+          echo "      - "`cat ssh-key` >> init-data
+          echo "power_state:">> init-data
+          echo "    mode: poweroff">> init-data
+          cat init-data
+          cloud-localds init.img init-data init-meta
+      - name: Download and unpack target OS cloud image
+        run: |
+          wget -nv https://cdimage.debian.org/images/cloud/bullseye/latest/debian-11-generic-amd64.tar.xz
+          mkdir img
+          tar -xf debian-11-generic-amd64.tar.xz -C img
+      - name: Run target OS (for cloud-init actions)
+        run: qemu-system-x86_64 -accel kvm -m 2048 -nographic -drive format=raw,file=img/`ls -1 img` -drive format=raw,file=init.img
+
   Build-and-Test:
-    #if: ${{ false }} # disable for now
+    if: ${{ false }} # disable for now
     strategy:
       fail-fast: false
       matrix:
@@ -60,7 +97,7 @@ jobs:
         run: sudo python3 -m pytest -Wall -v
 
   Build-and-Test-With-Coverage:
-    #if: ${{ false }} # disable for now
+    if: ${{ false }} # disable for now
     strategy:
       fail-fast: false
       matrix:
